# Generated by Django 3.2.7 on 2021-09-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=122)),
                ('standard', models.IntegerField(max_length=122)),
                ('totalmarks', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
