# Generated by Django 3.2.7 on 2021-09-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='standard',
            field=models.IntegerField(),
        ),
    ]
